logging:
  file: log/app.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] -%msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] [%thread] %-5level %logger{40}-%msg%n'
spring.profiles: local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoping?useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 50
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        proc:
          param_null_passing: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
      format_sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: noreply@abcd.com
    password: ***********
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        transport:
          protocol: smtp
#  redis:
#    database: 0
#    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  task:
    scheduling:
      pool:
        size: 20
  logging:
    level:
      org:
        hibernate:
          type: trace
      
